travis:
  secure:
    BINSTAR_TOKEN: nBez07Q8RbRxQlgfVoKQLx2pwhoijqIjxTpoRdzSy1VKFSzKrnbXtwymD6Di9luzuzFjlCKhN5MgV2+WF3S2Zuuh+LfBx2wFvCo4kn5IE1q6rL20dVjDMubuco8X8rj8XoG01XUoYJZvi4Yuso7b6xS0ayy/QXTsb8MKnREyRGr0WNWTepP7HX2G71fs3wKD2dak2b5BDI60MCCYjQAVG9+WlSLAbNjWCCYslNClrh7rslljp/t7Zny2rXItnleKxFlDGI5vADaPmD6Oh6Md0B7oGv/qkjQlju/6oHDuA/3pQoX4ViBDfuSH8Sgz8krEWT4Hr7p3EVnM1fGL9DfUiR3N9MoMqlocHc160RTwhM+7THUbT87YV4MlCSH0CfsvWhLQ4nvI3zDF1ujQhLEqQ5dlmigjKypqXt6/CvF+oztxHSuur1bHwl46OoBtNlg2L7I7K1JURb+gul9zpCOC7cb8LwD55ZgsJ0+O3LHEUAzX8FGG9mt0XaL9l2Xh8a2fRPZWE6gPIIrhaYwh9PzFoh8GIPezjP8D6KsWwVGkhMEvFNmmkAm1v//MnPiKeddPieJXtRyPueASOFtPG+skbm7itjG7Wj0WuzxpLRn4VdvTYesF43i8/Q3OMm12clzJsKiDb65BBHX/38NFW6sEllDZJcIH1y1W7i7ECku6o5E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
